# Generated by Django 5.2.12 on 2026-03-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aqireading',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='aqireading',
            old_name='aqi',
            new_name='aqi_value',
        ),
        migrations.RenameField(
            model_name='aqireading',
            old_name='recorded_at',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='aqireading',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('sensor', 'Sensor'), ('import', 'Import')], default='manual', help_text='How this AQI reading was created.', max_length=16),
        ),
    ]
